### ISSUE TITLE
Failing tests under Windows

### ISSUE THREAD

**Issue by mrbean-bremen** [jmcgeheeiv/pyfakefs#78]
If I run the test suite (all_tests) locally under Windows (Python 2.7), some of the tests fail due to path separator mismatch.
 I'm not sure if it is a problem of the tests or the code, or I do something wrong. Do you have any idea? 
 
 Here is the relevant output from a test run under Windows:
  ======================================================================
 ERROR: test_shutil (fake_filesystem_unittest_test.TestPyfakefsUnittest)
 Fake shutil module is bound
  ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "..\pyfakefs\fake_filesystem_unittest_test.py", line 92, in test_shutil
   File "..\pyfakefs\pyfakefs\fake_filesystem_shutil.py", line 79, in rmtree
   File "\pyfakefs\pyfakefs\fake_filesystem.py", line 902, in RemoveObject
 IOError: [Errno 2] No such file or directory in the fake filesystem: '/test/dir1'
 
  ======================================================================
 ERROR: test_rm_tree (example_test.TestExample)
 Test example.rm_tree()
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "..\pyfakefs\example_test.py", line 133, in test_rm_tree
   File "..\pyfakefs\example.py", line 121, in rm_tree
   File "..\pyfakefs\pyfakefs\fake_filesystem_shutil.py", line 79, in rmtree
   File "..\pyfakefs\pyfakefs\fake_filesystem.py", line 902, in RemoveObject
 IOError: [Errno 2] No such file or directory in the fake filesystem: '/test/dir1'
 
 ======================================================================
 FAIL: testExpandUser (fake_filesystem_test.FakePathModuleTest)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "..\pyfakefs\fake_filesystem_test.py", line 1897, in testExpandUser
     self.os.environ['USERPROFILE'].replace('\\', '/'))
 AssertionError: 'C:\\Users\\username' != 'C:/Users/username'
 
 ======================================================================
 FAIL: test_glob (fake_filesystem_unittest_test.TestPyfakefsUnittest)
 Fake glob module is bound
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "..\pyfakefs\fake_filesystem_unittest_test.py", line 80, in test_glob
 AssertionError: Lists differ: ['/test/dir1\\dir2a'] != ['/test/dir1/dir2a']
 
 ======================================================================
 FAIL: test_get_globs (example_test.TestExample)
 Test example.get_glob()
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "..\pyfakefs\example_test.py", line 118, in test_get_globs
 AssertionError: Lists differ: ['/test/dir1\\dir2a', '/test/d... != ['/test/dir1/dir2a', '/test/di...
 
 ======================================================================
 FAIL: get_glob (example)
 Doctest: example.get_glob
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "C:\Python27\lib\doctest.py", line 2226, in runTest
 AssertionError: Failed doctest test for example.get_glob
   File "..\pyfakefs\example.py", line 106, in get_glob
 
 ----------------------------------------------------------------------
 File "..\pyfakefs\example.py", line 114, in example.get_glob
 Failed example:
     get_glob('/test/file*.txt')
 Expected:
     ['/test/file1.txt', '/test/file2.txt']
 Got:
     ['/test\\file1.txt', '/test\\file2.txt']
 
 
 ----------------------------------------------------------------------
 Ran 413 tests in 0.273s
 
 FAILED (failures=4, errors=2, skipped=22)

**Comment by jmcgeheeiv** [comment]
I would have thought that your pull request #77 addresses this.  Do you get these results before or after applying #77?

**Comment by mrbean-bremen** [comment]
These are still there after applying the pull request. I will check if I can fix at least some of them - I guess you don't have a Windows test system. 
One question (more may follow): in testExpandUser() the original os.path.expanduser() is tested - to fix this, it may be replaced in the fake file system (probably by calling the original version and adapting the path afterwards). Is this the way you would handle this? If yes, I would give it a try, likewise for the other problems.

**Comment by mrbean-bremen** [comment]
Ok, I fixed most of the problems in #77, except the 2 failing doc tests. As their outcome is path separator-specific, they could be adapted something like TestPyfakefsUnittest.test_glob(), but this would be quite ugly in a doc string. 
Any idea how to fix this more nicely or at least just disable it under Windows?

**Comment by jmcgeheeiv** [comment]
That's great progress.

Which doctest is this that is failing?

**Comment by mrbean-bremen** [comment]
The last one (File "..\pyfakefs\example.py", line 114, in example.get_glob).
The problem here is that the expected output is different in Windows (due to the different path separator).

**Comment by jmcgeheeiv** [comment]
I see.  example.py is my file so I'll fix it.

**Comment by mrbean-bremen** [comment]
Ok, thanks. You could also just make it a normal comment instead of a doc test, as there is already a similar unit test.
I'm done with pull request #77 in this case - if you decide to merge it, it shall also fix issue #28.

**Comment by jmcgeheeiv** [comment]
I fixed example.py with what I hope is a cross-platform doctest.

Could you try out pull request #82?  Thank you.

**Comment by mrbean-bremen** [comment]
Still does not work correctly. The one that works for me (in Python 2.7) is the following: 
```
    >>> # Get the expected file names in the platform's native style
    >>> (file_names == ['/test/file1.txt', '/test/file2.txt']   # UNIX-like
    ...      or file_names == [r'\\test\\file1.txt', r'\\test\\file2.txt']) # Windows
    True
```
First, the logic was incorrect (the result of the or was always the first string), but the more ugly problem is the escaping in doc strings - it seems that you need to add an escape due to the text parsing.
I have no experience in doc strings, so maybe you have a better idea...

**Comment by jmcgeheeiv** [comment]
Please give it another go.

**Comment by mrbean-bremen** [comment]
Thanks  - as far as I can see, this should almost be ok, apart from the missing extra escape for the backslashes  (as mentioned above). I may check it again tomorrow - too late for today, time to sleep...

**Comment by mrbean-bremen** [comment]
Here is the output under Windows:
```
File "...\pyfakefs\example.py", line 116, in example.get_glob
Failed example:
    file_names == (['/test/file1.txt', '/test/file2.txt']   # UNIX-like
                       or
                   [r'      estile1.txt', r'       estile2.txt']) # Windows
Expected:
    True
Got:
    False
```
It works if I change it to:
```
    >>> file_names == (['/test/file1.txt', '/test/file2.txt']   # UNIX-like
    ...                    or
    ...                [r'\\test\\file1.txt', r'\\test\\file2.txt']) # Windows
    True
```
(e.g. insert extra escapes before the backslashes), or if not If not using raw strings:
`    ...                ['\\\\test\\\\file1.txt', '\\\\test\\\\file2.txt']) # Windows
`

**Comment by mrbean-bremen** [comment]
After the latest update I get a new failed test:
```
Traceback (most recent call last):
  File "..pyfakefs\fake_filesystem_test.py", line 2158, in testGetattrForwardToRealOsPath
    'Get a real os.path function not implemented in fake os.path')
AssertionError: Get a real os.path function not implemented in fake os.path
```
Can _joinrealpath() be platform specific?

**Comment by mrbean-bremen** [comment]
Whoops - I have to apologize! Your previous commit for the doc test (before you added my "fix") was completely ok. The mysterious behavior with the additional escape needed was due to an "r" I somehow managed to put before the docstring itself (and completely failed to see afterwards). 
So if you revert your last commit and merge PR #85 this issue shall be fixed. Sorry for the inconvenience...

**Comment by jmcgeheeiv** [comment]
Backslashes removed.

**Comment by mrbean-bremen** [comment]
All tests passing now  - closing.
